UI Detail + Reading
kekkei9/mangahay-fe pull request #2
Opened 2023-05-15 10:28 UTC by hihivipzz

2023-05-15 10:49 UTC, kekkei9 requested changes

2023-05-15 10:49 UTC, kekkei9 commented on src/components/Chapter/ChapterNav.tsx
> +          setShowNavbar(false);
setShowNavbar(scrollTop <= 0)

2023-05-15 10:49 UTC, kekkei9 commented on src/components/Chapter/ChapterNav.tsx
> +    const handleReport = (id:any)=>{
//TODO

2023-05-15 10:49 UTC, kekkei9 commented on src/components/Chapter/ChapterNav.tsx
> +        <nav className={`fixed w-full grid grid-cols-3 items-center py-2 gap-4 bg-zinc-800 visibility: ${showNavbar? 'visible':'hidden'}`} >
${showNavbar && 'hidden'}

2023-05-15 10:49 UTC, kekkei9 commented on src/components/Chapter/ChapterNav.tsx
> +            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 text-white mx-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
move to public

2023-05-15 10:49 UTC, kekkei9 commented on src/components/Chapter/ComicImages.tsx
> +                style={{ maxWidth: '100%', minWidth: '80%' }}
tailwind

2023-05-15 10:49 UTC, kekkei9 commented on src/components/ComicDetails/BodyComicAuthor.tsx
> +            <img src={props.comic.thumb} alt="" />
alt

2023-05-15 10:49 UTC, kekkei9 commented on src/components/ComicDetails/BodyComicAuthor.tsx
> +            <div className='text-black hover:none'>
remove hover:none

2023-05-15 10:49 UTC, kekkei9 commented on src/components/ComicDetails/ComicChapter.tsx
> +                        <li key={chap.num} className="flex justify-between items-center py-2 border-b border-gray-200">
remove items center

2023-05-15 10:49 UTC, kekkei9 commented on src/components/ComicDetails/EnvalueStar.tsx
> +const EnvalueStar = (props:any) =>{
spread

2023-05-15 10:49 UTC, kekkei9 commented on src/components/ReportTable/ReportTable.tsx
> +    const [selectedItems, setSelectedItems] = useState(props.items.map(() => false));
selectedId useState([])

2023-05-15 10:49 UTC, kekkei9 commented on src/pages/test/index.tsx
> +      <div className="bg-top bg-left bg-no-repeat bg-cover " style={{backgroundImage:"url('assets/comic/cover_test.jpg')"}}>
bg-[url]

2023-05-15 10:49 UTC, kekkei9 commented on src/pages/comic/[id]/[chap].tsx
> +                <CommentBox></CommentBox>
self closing

2023-05-15 12:10 UTC, hihivipzz commented on src/components/Chapter/ChapterNav.tsx
> +          setShowNavbar(false);
useEffect(() => {
      const handleScroll = () => {
        const scrollTop = window.pageYOffset;
        setShowNavbar(scrollTop <= 0)
      };
      const handleMouseMove = (e:any) => {
          setShowNavbar(e.clientY <= 50);
      };
      window.addEventListener("scroll", handleScroll);
      document.addEventListener("mousemove", handleMouseMove);
      return () =>{
           window.removeEventListener("scroll", handleScroll);
           document.removeEventListener("mousemove", handleMouseMove);
      }
    }, []);

2023-05-15 12:11 UTC, hihivipzz commented on src/components/Chapter/ChapterNav.tsx
> +    const handleReport = (id:any)=>{
//TODO: Gửi Report đến BE

2023-05-15 12:14 UTC, hihivipzz commented on src/components/Chapter/ChapterNav.tsx
> +        <nav className={`fixed w-full grid grid-cols-3 items-center py-2 gap-4 bg-zinc-800 visibility: ${showNavbar? 'visible':'hidden'}`} >
return (
      <>
         {reportIsShown && <ReportTable items={reportItems} onClose={closeReport}></ReportTable>}
        <nav className={`fixed w-full grid grid-cols-3 items-center py-2 gap-4 bg-zinc-800 visibility: ${showNavbar?&&'hidden`} >

2023-05-15 15:47 UTC, hihivipzz commented on src/components/Chapter/ComicImages.tsx
> +                style={{ maxWidth: '100%', minWidth: '80%' }}
className = "p-10 max-w-[100%] min-w-[80%]"

2023-05-15 15:53 UTC, hihivipzz commented on src/components/ComicDetails/BodyComicAuthor.tsx
> +            <img src={props.comic.thumb} alt="" />
alt="cover{props.comic.slug}"

2023-05-15 15:53 UTC, hihivipzz commented on src/components/ComicDetails/BodyComicAuthor.tsx
> +            <div className='text-black hover:none'>
<div className='text-black'>

2023-05-15 15:55 UTC, hihivipzz commented on src/components/ComicDetails/ComicChapter.tsx
> +                        <li key={chap.num} className="flex justify-between items-center py-2 border-b border-gray-200">
className="flex justify-between py-2 border-b border-gray-200"

2023-05-15 15:56 UTC, hihivipzz commented on src/pages/comic/[id]/[chap].tsx
> +                <CommentBox></CommentBox>
<CommentBox/>

2023-05-15 15:57 UTC, hihivipzz commented on src/pages/test/index.tsx
> +      <div className="bg-top bg-left bg-no-repeat bg-cover " style={{backgroundImage:"url('assets/comic/cover_test.jpg')"}}>
<div className="bg-top bg-left bg-no-repeat bg-cover bg-assets/comic/cover_test.jpg" >

2023-05-19 12:28 UTC, kekkei9 commented on package.json
> +    "antd": "^5.4.7",
where do u use antd?

2023-05-19 12:30 UTC, kekkei9 commented on src/components/Chapter/ChapterNav.tsx
> +        <nav className={`fixed w-full grid grid-cols-3 items-center py-2 gap-4 bg-zinc-800 visibility: ${showNavbar? 'visible':'hidden'}`} >
it still there

2023-05-19 12:30 UTC, kekkei9 commented on src/components/Chapter/ChapterNav.tsx
> +                <img src="/svg/RightArrow.svg" alt="Arrow" style={{ filter: 'invert(100%)' }}/>
invert -> tailwind

2023-05-19 12:30 UTC, kekkei9 commented on src/components/Chapter/ChapterNav.tsx
> +                <img src="/svg/LeftArrow.svg" alt="Arrow" style={{ filter: 'invert(100%)' }}/>
use faws icon / prime icon instead !

2023-05-19 12:32 UTC, kekkei9 commented on src/pages/test/index.tsx
> +      <div className="bg-top bg-left bg-no-repeat bg-cover " style={{backgroundImage:"url('assets/comic/cover_test.jpg')"}}>
it still there

2023-05-19 12:35 UTC, hihivipzz commented on src/pages/test/index.tsx
> +      <div className="bg-top bg-left bg-no-repeat bg-cover " style={{backgroundImage:"url('assets/comic/cover_test.jpg')"}}>
này file test đằng nào cũng xóa
t quăng componet zo đây để test thôi

2023-06-08 04:19 UTC, merged